import {
  Accessibility,
  Activity,
  AlarmClock,
  Archive,
  ArrowLeftRight,
  BadgeCheck,
  BadgeEuro,
  Barcode,
  Bell,
  Blend,
  Bookmark,
  BookCopy,
  BookMarked,
  BookOpen,
  Bot,
  Boxes,
  BriefcaseBusiness,
  Building2,
  Calculator,
  CalendarClock,
  CalendarDays,
  ChartNoAxesCombined,
  ChartPie,
  CheckCheck,
  ClipboardCheck,
  ClipboardList,
  Clock3,
  CloudOff,
  Coins,
  Columns3,
  Copy,
  CreditCard,
  Crown,
  DatabaseBackup,
  DatabaseZap,
  FileChartColumn,
  FileCheck2,
  FileClock,
  FileInput,
  FileOutput,
  FileSignature,
  FileSpreadsheet,
  FileText,
  Fingerprint,
  FolderSearch2,
  FolderTree,
  Gauge,
  GitCompareArrows,
  HandCoins,
  History,
  Import,
  Inbox,
  KeyRound,
  Landmark,
  Languages,
  Layers,
  Layers3,
  Library,
  Link2,
  ListChecks,
  MailCheck,
  MapPinned,
  MessageSquareText,
  Package,
  PackageCheck,
  PanelTop,
  Paperclip,
  Percent,
  PiggyBank,
  PlugZap,
  QrCode,
  Receipt,
  RefreshCcw,
  Repeat2,
  Scale,
  ScanText,
  Send,
  ServerCog,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Signature,
  Stamp,
  Store,
  Tags,
  TimerReset,
  TrendingUp,
  TriangleAlert,
  Truck,
  Undo2,
  UserCog,
  UserPlus,
  Vault,
  Webhook,
  Workflow,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

export const featureIcons: Record<string, LucideIcon> = {
  'document-tracking': FileClock,
  recurring: Repeat2,
  usage: Gauge,
  duplicate: Copy,
  proforma: FileText,
  'sales-orders': ShoppingCart,
  deliveries: Truck,
  'partial-billing': Columns3,
  simplified: Receipt,
  'advance-invoice': HandCoins,
  'price-correction': RefreshCcw,
  'self-billing': FileCheck2,
  currencies: Coins,
  disbursements: Percent,
  'saved-views': Bookmark,
  'batch-actions': CheckCheck,
  conflicts: GitCompareArrows,

  'quote-revisions': History,
  'quote-renewal': TimerReset,
  'quote-partial': ChartPie,
  signature: Signature,

  ocr: ScanText,
  'purchase-orders': ClipboardList,
  'purchase-receipts': PackageCheck,
  'three-way': GitCompareArrows,
  'expense-reports': Receipt,
  'accrued-purchases': CalendarClock,
  'purchase-comparison': Scale,
  'purchase-coding': Calculator,
  'payment-approval': BadgeCheck,

  'bank-accounts': Landmark,
  'bank-import': FileInput,
  reconciliation: Blend,
  'internal-transfer': ArrowLeftRight,
  'bank-rules': Workflow,
  'bank-incidents': TriangleAlert,
  'sepa-mandates': FileSignature,
  'sepa-batches': Layers3,
  'payment-orders': ListChecks,
  'online-payments': Link2,
  settlements: CreditCard,
  'payment-returns': Undo2,
  disputes: ShieldAlert,
  offsetting: Scale,
  financing: PiggyBank,
  'payment-history': History,

  'fiscal-identity': Fingerprint,
  'buyer-formats': Paperclip,

  'price-lists': Tags,
  'price-tiers': BadgeEuro,
  units: Scale,
  variants: Barcode,
  bundles: Boxes,
  'cost-margin': TrendingUp,
  categories: FolderTree,

  'accounting-templates': BookCopy,
  subledgers: BookMarked,
  accruals: CalendarClock,
  'financial-year': CalendarDays,
  journals: Library,
  dimensions: ChartPie,
  'annual-reports': FileChartColumn,
  'continuous-close': ClipboardCheck,

  'tax-profile': MapPinned,
  'tax-rules': Percent,
  deductibility: Calculator,
  'fiscal-connectors': PlugZap,
  'fiscal-submissions': Send,
  'tax-books': BookOpen,

  'template-layout': PanelTop,
  'template-locales': Languages,
  'accessible-pdf': Accessibility,
  'sender-permissions': MailCheck,
  'document-conversation': MessageSquareText,

  'spreadsheet-options': FileSpreadsheet,
  'master-updates': DatabaseZap,
  'historical-import': Import,
  'file-quarantine': ShieldCheck,
  'import-resolution': Wrench,
  'document-export': FileOutput,

  'automation-rules': Workflow,
  reminders: Bell,
  'job-supervision': Activity,
  'assistance-policy': Bot,

  'work-inbox': Inbox,
  'unbilled-work': BriefcaseBusiness,
  aging: AlarmClock,
  'cash-forecast': ChartNoAxesCombined,
  'custom-reports': FileChartColumn,
  'global-document-search': FolderSearch2,

  assets: Vault,
  inventory: Package,
  'projects-time': Clock3,
  commissions: BadgeEuro,
  'group-companies': Building2,
  intercompany: ArrowLeftRight,
  'pos-terminal': QrCode,
  'pos-sale': ShoppingCart,
  'pos-cash': Store,
  offline: CloudOff,

  invitations: UserPlus,
  'account-recovery': KeyRound,
  'fine-permissions': ShieldCheck,
  'configuration-history': History,
  capabilities: Gauge,
  representation: Stamp,
  advisors: BriefcaseBusiness,
  ownership: Crown,
  retention: Archive,
  'support-access': UserCog,
  'security-incidents': ShieldAlert,

  'public-api': Webhook,
  connectors: PlugZap,
  'backup-recovery': DatabaseBackup,
  operations: ServerCog,
};

export function featureIcon(feature: { id: string }): LucideIcon {
  return featureIcons[feature.id] || Layers;
}
